In [1]:
import numpy as np

In [2]:
a = np.ones([4,4], dtype = bool)
a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [3]:
a = np.arange(10)
b = (a%2 == 1)
a[b] = -1
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
a = np.array([54,27,34,87,99,12])
print(np.max(a))
print(np.min(a))

99
12


In [5]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [6]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(b,a))

[6 7 8 9]
